version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 08012005
      MYSQL_DATABASE: SGr
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306" # Sử dụng cổng mặc định của MySQL
    expose:
        - 3306


  vantien8105:
      depends_on:
        - db
      image: vantien8105:latest
      restart: always
      environment:
        - DB_HOST=db
        - DB_PORT=3306
        - DB_USER=root
        - DB_PASSWORD=${passwordDB}
        - DB_DATABASE=${nameDB}
      env_file:
        - .env
      ports:
        - "3000:3000"
  backend:
    build:
       context: ../../rsc
       dockerfile: dockerfile
    restart: unless-stopped
    environment:
      - DB_HOST = host.docker.internal 
    ports:
      - "3306:3306"
volumes:
  db_data: