

name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and test
        run: |
          docker build -t vantien8105 -f rsc/Dockerfile .
          docker run vantien8105 npm test

      - name: Push image to Docker Hub
        uses: docker/build-push-action@v2
        # Sử dụng action "docker/build-push-action" để đẩy image lên Docker Hub
        with:
          context: .
          push: true
          tags: vantien8105/vantien8105:latest
          file: ./rsc/Dockerfile
  # Job 2: Deploy
  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create SSH key file
        run: |
          mkdir -p $HOME/.ssh
          echo "$SSH_PRIVATE_KEY" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa

      - name: Deploy to server
        run: |
          echo "$SSH_PRIVATE_KEY" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa
          ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} << 'EOF'
          sudo docker pull vantien8105/rsc-backend:latest
          sudo docker stop my_container || true
          sudo docker rm my_container || true
          sudo docker run -d -p 3000:3000 --name my_container \
            -e DB_HOST=db \
            -e DB_PORT=3306 \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e nameDB=${{ secrets.NAMEDB }} \
            -e passwordDB=${{ secrets.PASSWORDDB }} \
            vantien8105/rsc-backend:latest
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      # - name: Deploy to server
      #  # Sử dụng action "appleboy/ssh-action" để triển khai image lên server thông qua SSH
      #   uses: appleboy/ssh-action@v0.1.3
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       # Pull image mà được push lên DockerHub bên trên
      #       docker pull ${{ secrets.DOCKERHUB_USERNAME }}/reactjs-basic:${{ commit }}

      #       # Dừng và gỡ bỏ container hiện tại (nếu có)
      #       docker stop reactjs-container
      #       docker rm reactjs-container 

      #       # Chạy container mới với image đã pull về bên trên
      #       docker run -d -p 3000:3000 --name reactjs-container ${{ secrets.DOCKERHUB_USERNAME }}/reactjs-basic:${{ "commit"}}


